# Generated by Django 3.2.7 on 2021-09-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('InShop', 'InShop')], max_length=64)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Critical', 'Critical')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Consum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vehicle')),
            ],
        ),
    ]
